### ISSUE TITLE
Accept Select Ingredient Dropdown Input as a argument for the Search By Ingredients Function

### ISSUE THREAD

**Issue by Slyssy** [Slyssy/cocktails#1]
We need to select a drink ingredient, and set that value to the ingredient variable.

**Comment by Slyssy** [comment]
We also need to create a submit button that will be used to call the searchByIngredient function.

**Comment by LeahMarke** [comment]
this issue has been solved. getting ready to issue a pull request

**Comment by LeahMarke** [comment]
Issue #1 solved by Leah Marke
